# Site
site_name: Aayush Uppal
copyright: '© Aayush Uppal'
site_description: Aayush Uppal Blog & Personal Website
site_author: Aayush Uppal
site_url: https://aayushuppal.github.io/site

# Repository
# repo_name: aayushuppal/site
# repo_url: https://github.com/aayushuppal/site
# edit_uri: blob/master/docs/

extra_css:
  - 'stylesheets/flexboxgrid.min.css'
  - 'stylesheets/extra.css'
  - 'https://use.fontawesome.com/releases/v5.0.13/css/all.css'

extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js"
  - "https://platform.twitter.com/widgets.js"
  - "js/extra-seq.js"

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: 'material'
  palette:
    primary: 'white'
    accent: 'indigo'
  favicon: 'img/favicon.ico'
  logo:
    icon: 'explore'
  feature:
    tabs: true

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  language: en
  font:
    text: Monospace
    code: Monospace

google_analytics:
  - 'UA-118033019-1'
  - 'auto'

pages:
  - Home: index.md
  - Profile: profile.md
  - Extras: extras.md
  - Lists: lists.md
  - Contact: contact.md

  - Dev Posts:
    - Multi Threading Python: devposts/multi_threading_python.md
    - Multiple Git Accounts: devposts/multiple_git.md
    - DP/Pg/I: devposts/devposts1.md
    - Root & Custom Rom Android: devposts/root-rom-samsung.md

  - Blog:
    - Mantra - I: blog/mantra-i.md
    - The Dying Art of Disagreement: blog/art_disagreement.md
    - Kangra Valley Train: blog/kangra-valley-train.md
    - Representations: blog/representations.md
    - This Developer Life: blog/this_dev_life.md
    - Not All Shadows: blog/not_all_shadows.md
    - Calm of the Qualm: blog/calm_qualm.md
    - Road Back Home: blog/road_back_home.md
    - Colors of Foliage: blog/colors_of_foliage.md
    # - Ordinary Emotion: blog/ordinary-emotion.md
